name: Verify Runtime Setup
description: Reports runtime setup results and validates expectations

inputs:
  title:
    description: Title for the test results section (including emoji)
    required: true
  outputs:
    description: JSON string of all setup outputs from steps.setup.outputs
    required: true

  # Expected values for validation
  expected-runtime:
    description: Expected runtime value
    required: false
  expected-package-manager:
    description: Expected package manager value
    required: false
  expected-node-version:
    description: Expected Node.js version
    required: false
  expected-node-version-file:
    description: Expected version file
    required: false
  expected-bun-version:
    description: Expected Bun version
    required: false
  expected-deno-version:
    description: Expected Deno version
    required: false
  expected-biome-enabled:
    description: Expected biome-enabled value
    required: false
  expected-biome-version:
    description: Expected biome version
    required: false
  expected-biome-config-file:
    description: Expected biome config file
    required: false
  expected-turbo-enabled:
    description: Expected turbo-enabled value
    required: false
  expected-turbo-config-file:
    description: Expected turbo config file
    required: false
  expected-cache-hit:
    description: Expected cache hit status
    required: false

runs:
  using: composite
  steps:
    - name: Verify and report
      shell: bash
      run: |
        echo "## ${{ inputs.title }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        FAILED=0

        # Parse outputs JSON
        OUTPUTS='${{ inputs.outputs }}'

        # Helper function to get value from JSON
        get_output() {
          echo "$OUTPUTS" | jq -r ".[\"$1\"] // empty"
        }

        # Helper function to check and report a value
        check_value() {
          local key="$1"
          local expected="$2"

          local actual=$(get_output "$key")

          # Skip if no actual value
          if [ -z "$actual" ]; then
            return
          fi

          # Show the key and value
          echo -n "$key: $actual " >> $GITHUB_STEP_SUMMARY

          # If expected value is provided, validate it
          if [ -n "$expected" ]; then
            if [ "$actual" = "$expected" ]; then
              echo "✅" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ (expected: $expected)" >> $GITHUB_STEP_SUMMARY
              FAILED=1
            fi
          else
            # Neutral check - no expectation
            echo "✔️" >> $GITHUB_STEP_SUMMARY
          fi
        }

        # Report all values with optional validation
        check_value "runtime" "${{ inputs.expected-runtime }}"
        check_value "package-manager" "${{ inputs.expected-package-manager }}"
        check_value "node-version" "${{ inputs.expected-node-version }}"
        check_value "node-version-file" "${{ inputs.expected-node-version-file }}"
        check_value "node-version-source" ""
        check_value "bun-version" "${{ inputs.expected-bun-version }}"
        check_value "deno-version" "${{ inputs.expected-deno-version }}"
        check_value "biome-enabled" "${{ inputs.expected-biome-enabled }}"
        check_value "biome-version" "${{ inputs.expected-biome-version }}"
        check_value "biome-config-file" "${{ inputs.expected-biome-config-file }}"
        check_value "turbo-enabled" "${{ inputs.expected-turbo-enabled }}"
        check_value "turbo-config-file" "${{ inputs.expected-turbo-config-file }}"
        check_value "cache-hit" "${{ inputs.expected-cache-hit }}"

        echo "" >> $GITHUB_STEP_SUMMARY

        # Report final status
        if [ $FAILED -eq 0 ]; then
          echo "✅ All validations passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some validations failed" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
