name: "Setup JavaScript Runtime Environment"
description: "Comprehensive JavaScript runtime setup (Node.js, Bun, Deno) configured via package.json devEngines.runtime, with dependency caching, Turbo build cache, and optional Biome linter configuration"

branding:
  icon: "package"
  color: "green"

inputs:
  node-version:
    description: "Node.js version to install (e.g., '24.10.0'). If not provided, reads from package.json devEngines.runtime."
    required: false
    default: ""
  bun-version:
    description: "Bun version to install (e.g., '1.3.3'). If not provided, reads from package.json devEngines.runtime."
    required: false
    default: ""
  deno-version:
    description: "Deno version to install (e.g., '2.5.6'). If not provided, reads from package.json devEngines.runtime."
    required: false
    default: ""
  package-manager:
    description: "Package manager name (npm | pnpm | yarn | bun | deno). If not provided, reads from package.json devEngines.packageManager."
    required: false
    default: ""
  package-manager-version:
    description: "Package manager version (e.g., '10.20.0'). If not provided, reads from package.json devEngines.packageManager."
    required: false
    default: ""
  biome-version:
    description: "Biome version to install (e.g., '2.3.6'). If not provided, auto-detects from biome.jsonc or biome.json. Leave empty to skip."
    required: false
    default: ""
  turbo-token:
    description: "Turbo remote cache token (optional, for Vercel Remote Cache)"
    required: false
    default: ""
  turbo-team:
    description: "Turbo team slug (optional, for Vercel Remote Cache)"
    required: false
    default: ""
  install-deps:
    description: "Whether to install dependencies (true | false). Set to false to skip dependency installation."
    required: false
    default: "true"
  cache-hash:
    description: "Optional cache hash for testing. Use github.run_id to ensure unique cache per run. Only use this for testing cache behavior."
    required: false
    default: ""

outputs:
  node-version:
    description: "The Node.js version that was installed (e.g., '24.10.0' or empty if not installed)"
  node-enabled:
    description: "Whether Node.js was installed (true | false)"
  bun-version:
    description: "The Bun version that was installed (e.g., '1.3.3' or empty if not installed)"
  bun-enabled:
    description: "Whether Bun was installed (true | false)"
  deno-version:
    description: "The Deno version that was installed (e.g., '2.5.6' or empty if not installed)"
  deno-enabled:
    description: "Whether Deno was installed (true | false)"
  package-manager:
    description: "The package manager name (npm | pnpm | yarn | bun | deno)"
  package-manager-version:
    description: "The package manager version (e.g., '10.20.0')"
  biome-version:
    description: "The Biome version that was installed (e.g., '2.3.6' or empty if not installed)"
  biome-enabled:
    description: "Whether Biome was installed (true | false)"
  turbo-enabled:
    description: "Whether Turbo configuration was detected (true | false)"
  cache-hit:
    description: "Whether dependencies were restored from cache (true | partial | false | n/a)"
  lockfiles:
    description: "Comma-separated list of detected lockfiles used for cache key generation (e.g., 'pnpm-lock.yaml,deno.lock')"
  cache-paths:
    description: "Comma-separated list of cache paths being cached/restored (e.g., '/home/runner/.cache/deno,**/node_modules')"

runs:
  using: "node24"
  main: "dist/main.js"
  post: "dist/post.js"
