name: "Setup Environment"
description: "Sets up Node.js, package manager (npm/pnpm/yarn) with caching, Turbo build cache, and installs dependencies"

inputs:
  package-manager:
    description: "Package manager to use (npm | pnpm | yarn). If omitted, will be detected from package.json packageManager field or lockfiles"
    required: false
    default: ""
  turbo-token:
    description: "Turbo remote cache token (optional, for Vercel Remote Cache)"
    required: false
    default: ""
  turbo-team:
    description: "Turbo team slug (optional, for Vercel Remote Cache)"
    required: false
    default: ""
  node-version:
    description: "Version Spec of the version to use in SemVer notation. It also admits such aliases as lts/*, latest, nightly and canary builds. Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node"
    required: false
    default: "lts/*"

outputs:
  runtime-version:
    description: "The Node.js runtime version that was installed"
    value: ${{ steps.env-info.outputs.version }}
  node-version-manager-file:
    description: "The Node.js version manager file that was detected (.nvmrc | .node-version | empty if using input)"
    value: ${{ steps.detect-config.outputs.node-version-file }}

runs:
  using: "composite"
  steps:
    - name: Mask sensitive inputs
      shell: bash
      run: |
        # Mask sensitive values to prevent exposure in logs
        if [[ -n "${{ inputs.turbo-token }}" ]]; then
          echo "::add-mask::${{ inputs.turbo-token }}"
        fi

    - name: Detect Node.js configuration
      id: detect-config
      uses: actions/github-script@v8
      env:
        INPUT_PACKAGE_MANAGER: ${{ inputs.package-manager }}
        INPUT_NODE_VERSION: ${{ inputs.node-version }}
      with:
        script: |
          const { default: detectNodeConfig } = await import('${{ github.action_path }}/detect-node-config.ts');
          await detectNodeConfig({ core });

    - name: Setup pnpm
      if: steps.detect-config.outputs.package-manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        standalone: true
        run_install: false

    - name: Display pnpm version
      if: steps.detect-config.outputs.package-manager == 'pnpm'
      shell: bash
      run: |
        PNPM_VERSION=$(pnpm --version)
        echo "::notice title=Package Manager::Using pnpm v$PNPM_VERSION"

    - name: Setup Yarn
      if: steps.detect-config.outputs.package-manager == 'yarn'
      shell: bash
      run: corepack enable yarn

    - name: Display Yarn version
      if: steps.detect-config.outputs.package-manager == 'yarn'
      shell: bash
      run: |
        YARN_VERSION=$(yarn --version)
        echo "::notice title=Package Manager::Using Yarn v$YARN_VERSION"

    - name: Setup Node.js (pnpm)
      id: setup-node-pnpm
      if: steps.detect-config.outputs.package-manager == 'pnpm'
      uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version: ${{ steps.detect-config.outputs.node-version }}
        node-version-file: ${{ steps.detect-config.outputs.node-version-file }}
        cache-dependency-path: |
          pnpm-lock.yaml
          pnpm-workspace.yaml
          .pnpmfile.cjs
          turbo.json
          .turbo

    - name: Setup Node.js (yarn)
      id: setup-node-yarn
      if: steps.detect-config.outputs.package-manager == 'yarn'
      uses: actions/setup-node@v6
      with:
        cache: yarn
        node-version: ${{ steps.detect-config.outputs.node-version }}
        node-version-file: ${{ steps.detect-config.outputs.node-version-file }}
        cache-dependency-path: |
          yarn.lock
          turbo.json
          .turbo

    - name: Setup Node.js (npm)
      id: setup-node-npm
      if: steps.detect-config.outputs.package-manager == 'npm'
      uses: actions/setup-node@v6
      with:
        cache: npm
        node-version: ${{ steps.detect-config.outputs.node-version }}
        node-version-file: ${{ steps.detect-config.outputs.node-version-file }}
        cache-dependency-path: |
          package-lock.json
          turbo.json
          .turbo

    - name: Output environment details
      id: env-info
      shell: bash
      run: |
        NODE_VERSION="${{ steps.setup-node-pnpm.outputs.node-version || steps.setup-node-yarn.outputs.node-version || steps.setup-node-npm.outputs.node-version }}"
        CACHE_HIT="${{ steps.setup-node-pnpm.outputs.cache-hit || steps.setup-node-yarn.outputs.cache-hit || steps.setup-node-npm.outputs.cache-hit }}"
        NODE_MAJOR=$(echo "$NODE_VERSION" | cut -d. -f1)
        NODE_VERSION_SOURCE="${{ steps.detect-config.outputs.node-version-source }}"
        NODE_VERSION_FILE="${{ steps.detect-config.outputs.node-version-file }}"

        echo "major=$NODE_MAJOR" >> $GITHUB_OUTPUT
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

        # Display Node.js version information
        if [[ "$NODE_VERSION_SOURCE" == "input" ]]; then
          echo "::notice title=Node.js Version::v$NODE_VERSION (from input, major: $NODE_MAJOR)"
        else
          echo "::notice title=Node.js Version::v$NODE_VERSION (from $NODE_VERSION_FILE, major: $NODE_MAJOR)"
        fi

        # Display cache status
        if [[ "$CACHE_HIT" == "true" ]]; then
          echo "::notice title=Dependency Cache::Cache hit - dependencies restored from cache"
        else
          echo "::notice title=Dependency Cache::Cache miss - will download dependencies"
        fi

    - name: Detect Turbo configuration
      id: turbo-check
      uses: savvy-web/.github-private/.github/actions/detect-turbo@feature/setup-flow

    - name: Configure Turbo remote cache
      if: steps.turbo-check.outputs.enabled == 'true' && inputs.turbo-token != '' && inputs.turbo-team != ''
      shell: bash
      run: |
        # Set environment variables for Turbo
        echo "TURBO_TOKEN=${{ inputs.turbo-token }}" >> $GITHUB_ENV
        echo "TURBO_TEAM=${{ inputs.turbo-team }}" >> $GITHUB_ENV
        echo "::notice title=Turbo Cache::Remote cache enabled for team ${{ inputs.turbo-team }}"

    - name: Display Turbo status
      if: steps.turbo-check.outputs.enabled == 'true' && (inputs.turbo-token == '' || inputs.turbo-team == '')
      shell: bash
      run: |
        echo "::notice title=Turbo Cache::Turbo detected but remote cache not configured (missing token or team)"

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Installing dependencies"
        echo "Running: ${{ steps.detect-config.outputs.install-command }}"
        ${{ steps.detect-config.outputs.install-command }}
        echo "::endgroup::"
        echo "::notice title=Dependencies::Dependencies installed successfully"
      env:
        DO_NOT_TRACK: "1"
        TURBO_TELEMETRY_DISABLE: "1"
