name: Setup Test Fixture
description: Prepare test environment by removing repository config and copying fixture files

inputs:
  fixture:
    description: Name of the fixture directory in __fixtures__/
    required: true

runs:
  using: composite
  steps:
    - name: Setup test environment
      shell: bash
      run: |
        # Remove repository config files
        rm -f package.json pnpm-workspace.yaml biome.jsonc turbo.json pnpm-lock.yaml .nvmrc .node-version deno.json deno.lock

        # Copy fixture files to current directory (including hidden files)
        cp -r __fixtures__/${{ inputs.fixture }}/. .

        echo "✓ Fixture '${{ inputs.fixture }}' prepared"
