name: "Detect Runtime"
description: "Detects JavaScript runtime (node/bun/deno) and package manager"

outputs:
  runtime:
    description: "Detected JavaScript runtime (node | bun | deno)"
    value: ${{ steps.detect.outputs.runtime }}
  package-manager:
    description: "Detected package manager (npm | pnpm | yarn | bun | deno)"
    value: ${{ steps.detect.outputs.package-manager }}

runs:
  using: "composite"
  steps:
    - name: Detect runtime and package manager
      id: detect
      uses: actions/github-script@v8
      with:
        script: |
          const { default: detectRuntime } = await import('${{ github.action_path }}/detect-runtime.ts');
          await detectRuntime({ core });
